### PR TITLE
[PR] Image upload demo initial implementation

### LINKED ISSUE #1: Epic: Upload Images from `Flutter` App to `S3` via `Phoenix`
Once we have basic image uploading working in `Phoenix + LiveView` [#51](https://github.com/dwyl/image-uploads/issues/51) (and deployed to Fly.io) 🚀 
The next logical step is to implement a `Flutter` front-end. 📱 
The most difficult part of this is:
a) uploading the `img` data to the `Phoenix` backend: https://kashifchandio.medium.com/upload-images-to-a-rest-api-with-flutter-using-http-61713964e1c appears to be a good starting point. But please do your own research to find any relevant sample code. 🙏 
b) Securing the uploads so that random people can't send data to the `Phoenix` upload API/backend. This should probably be something we handle server side. See: https://github.com/dwyl/image-uploads/issues/53
c) Visual feedback for the uploader indicating the approximate time it will take to process.

# Todo

+ [x] Create a new repo e.g: `flutter-image-upload-demo`  (this repo! ;-)
+ [x] Create a super basic App that has:
  + [x] A file picker that allows selecting photos on the device
  + [x] Selecting the file should automatically begin the upload, no button pressing required.
  + [x] Once the upload is complete, show a thumbnail of the image
  + [x] Add tests.
  + [x] Document everything.
  + [x] Fix the overflowing error when uploading large pictures
  
image

Fellow Tuga @miguelpruivo - rising star of @FlutterPortugal - he's built: [`flutter_file_picker`](https://github.com/miguelpruivo/flutter_file_picker )  
looks well-documented, tested & maintained. 😍 
We can use it for the file-picking part. 

> **Note**: we aren't building [imgur](https://imgur.com/gallery/odNLFdO) but certainly the foundation of it. 😜

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #1

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
This should be ready for review 👌

**Comment by nelsonic** [comment]
Thanks @LuchoTurtle I've added it to my list to review next. 📥 
What are you up to today? (catch up in 20 mins on standup...) 👌

**Comment by LuchoTurtle** [comment]
Assigning back to me to fix the error described in the edited description of https://github.com/dwyl/flutter-image-upload-demo/issues/1.

**Comment by LuchoTurtle** [comment]
The issue has been fixed. 
Should be mergeable now 👌

**Comment by nelsonic** [comment]
Somehow I didn't get this notification. 🤦‍♂️ 
Will review this ASAP. 🧑‍💻 ⏳

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle looks great! Thanks. 🎉 
Please add a link to the `GitHub Pages` deployed version of this when you can. 🙏

**Pull request merged**
